### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by bschelst** [gbro115/gloriafood-php#1]
The api works (based on examples.php). But the json doesn't contain the links to the image files.
The  json shoild include the image files too.

**Comment by gbro115** [comment]
Hi @bschelst,

I don't see the URLs in the JSON response returned from GloriaFood's API, and it's not documented in their repo.

Are you requesting that the URLs be included in the API's response, or that this package should be able to parse the data received from the API? 

Please note that this isn't an **official** GloriaFood package.

Thanks

**Comment by gbro115** [comment]
Closing issue due to lack of response.
